config/routes.rb
FirstApp::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  resources :fichiers

  resources :users

end

app/models/fichier.rb
class Fichier < ActiveRecord::Base
  attr_accessible :hashtag, :name, :size, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password
  has_many :fichiers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fichiers_controller.rb
class FichiersController < ApplicationController
  # GET /fichiers
  # GET /fichiers.json
  def index
    @fichiers = Fichier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fichiers }
    end
  end

  # GET /fichiers/1
  # GET /fichiers/1.json
  def show
    @fichier = Fichier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fichier }
    end
  end

  # GET /fichiers/new
  # GET /fichiers/new.json
  def new
    @fichier = Fichier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fichier }
    end
  end

  # GET /fichiers/1/edit
  def edit
    @fichier = Fichier.find(params[:id])
  end

  # POST /fichiers
  # POST /fichiers.json
  def create
    @fichier = Fichier.new(params[:fichier])

    respond_to do |format|
      if @fichier.save
        format.html { redirect_to @fichier, notice: 'Fichier was successfully created.' }
        format.json { render json: @fichier, status: :created, location: @fichier }
      else
        format.html { render action: "new" }
        format.json { render json: @fichier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fichiers/1
  # PUT /fichiers/1.json
  def update
    @fichier = Fichier.find(params[:id])

    respond_to do |format|
      if @fichier.update_attributes(params[:fichier])
        format.html { redirect_to @fichier, notice: 'Fichier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fichier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichiers/1
  # DELETE /fichiers/1.json
  def destroy
    @fichier = Fichier.find(params[:id])
    @fichier.destroy

    respond_to do |format|
      format.html { redirect_to fichiers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fichiers_helper.rb
module FichiersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fichiers/_form.html.erb
<%= form_for(@fichier) do |f| %>
  <% if @fichier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fichier.errors.count, "error") %> prohibited this fichier from being saved:</h2>

      <ul>
      <% @fichier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hashtag %><br />
    <%= f.text_field :hashtag %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.number_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fichiers/edit.html.erb
<h1>Editing fichier</h1>

<%= render 'form' %>

<%= link_to 'Show', @fichier %> |
<%= link_to 'Back', fichiers_path %>

app/views/fichiers/index.html.erb
<h1>Listing fichiers</h1>

<table>
  <tr>
    <th>Hashtag</th>
    <th>User</th>
    <th>Name</th>
    <th>Size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fichiers.each do |fichier| %>
  <tr>
    <td><%= fichier.hashtag %></td>
    <td><%= fichier.user_id %></td>
    <td><%= fichier.name %></td>
    <td><%= fichier.size %></td>
    <td><%= link_to 'Show', fichier %></td>
    <td><%= link_to 'Edit', edit_fichier_path(fichier) %></td>
    <td><%= link_to 'Destroy', fichier, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fichier', new_fichier_path %>

app/views/fichiers/new.html.erb
<h1>New fichier</h1>

<%= render 'form' %>

<%= link_to 'Back', fichiers_path %>

app/views/fichiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hashtag:</b>
  <%= @fichier.hashtag %>
</p>

<p>
  <b>User:</b>
  <%= @fichier.user_id %>
</p>

<p>
  <b>Name:</b>
  <%= @fichier.name %>
</p>

<p>
  <b>Size:</b>
  <%= @fichier.size %>
</p>


<%= link_to 'Edit', edit_fichier_path(@fichier) %> |
<%= link_to 'Back', fichiers_path %>

app/views/layouts/application.html.erb
<% provide(:title, 'Fatal Share') %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<img src="http://fatalshare.com/templates/Gemini/images/logotype.png" />

<%= yield %>

</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Fatal Share Help') %>
<h1>T'as besoin d'aide ?</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Home PAGE !!!! </h1>
<p>kiff tes upload</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>